// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'audio/device.dart';
import 'decode.dart';
import 'error.dart';
import 'export.dart';
import 'frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session.dart';
import 'settings.dart';

Future<String> engineVersion() => RustLib.instance.api.crateApiEngineVersion();

Future<bool> healthCheck() => RustLib.instance.api.crateApiHealthCheck();

Future<List<AudioDeviceInfo>> listAudioDevices() =>
    RustLib.instance.api.crateApiListAudioDevices();

Future<AudioDeviceInfo> getLoopbackDevice({required String nameHint}) =>
    RustLib.instance.api.crateApiGetLoopbackDevice(nameHint: nameHint);

Future<String> startSession({required SessionConfig config}) =>
    RustLib.instance.api.crateApiStartSession(config: config);

Future<void> stopSession({required String sessionId}) =>
    RustLib.instance.api.crateApiStopSession(sessionId: sessionId);

Future<void> toggleMic({required String sessionId, required bool enabled}) =>
    RustLib.instance.api.crateApiToggleMic(
      sessionId: sessionId,
      enabled: enabled,
    );

Future<void> toggleSpeaker({
  required String sessionId,
  required bool enabled,
}) => RustLib.instance.api.crateApiToggleSpeaker(
  sessionId: sessionId,
  enabled: enabled,
);

Future<void> setSessionMode({
  required String sessionId,
  required SessionMode mode,
}) => RustLib.instance.api.crateApiSetSessionMode(
  sessionId: sessionId,
  mode: mode,
);

Future<SessionStatus> getSessionStatus({required String sessionId}) =>
    RustLib.instance.api.crateApiGetSessionStatus(sessionId: sessionId);

Future<List<SessionEvent>> pollSessionEvents({required String sessionId}) =>
    RustLib.instance.api.crateApiPollSessionEvents(sessionId: sessionId);

Future<List<SessionRecoverySnapshot>> listRecoverableSessions() =>
    RustLib.instance.api.crateApiListRecoverableSessions();

Future<String> recoverSession({required SessionRecoverySnapshot snapshot}) =>
    RustLib.instance.api.crateApiRecoverSession(snapshot: snapshot);

Future<List<ModelInfo>> listAvailableModels({required String modelsDir}) =>
    RustLib.instance.api.crateApiListAvailableModels(modelsDir: modelsDir);

Future<bool> isModelDownloaded({
  required String modelsDir,
  required String modelId,
}) => RustLib.instance.api.crateApiIsModelDownloaded(
  modelsDir: modelsDir,
  modelId: modelId,
);

Future<void> downloadModel({
  required String modelsDir,
  required String modelId,
}) => RustLib.instance.api.crateApiDownloadModel(
  modelsDir: modelsDir,
  modelId: modelId,
);

Future<List<ExportedFile>> exportSession({
  required List<Segment> segments,
  required List<ExportFormat> formats,
  required String outputDir,
  required String title,
}) => RustLib.instance.api.crateApiExportSession(
  segments: segments,
  formats: formats,
  outputDir: outputDir,
  title: title,
);

Future<AudioBuffer> decodeAudioFile({required String path}) =>
    RustLib.instance.api.crateApiDecodeAudioFile(path: path);

Future<AppSettings> loadSettings() =>
    RustLib.instance.api.crateApiLoadSettings();

Future<void> saveSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateApiSaveSettings(settings: settings);

Future<bool> isAnotherInstanceRunning() =>
    RustLib.instance.api.crateApiIsAnotherInstanceRunning();

Future<void> acquireInstanceLock() =>
    RustLib.instance.api.crateApiAcquireInstanceLock();

Future<void> releaseInstanceLock() =>
    RustLib.instance.api.crateApiReleaseInstanceLock();
