// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

class SessionConfig {
  final bool micEnabled;
  final bool speakerEnabled;
  final SessionMode mode;
  final String? micDeviceId;
  final String? speakerDeviceId;
  final String modelPath;
  final bool vadEnabled;
  final int sampleRate;
  final int chunkDurationSecs;

  const SessionConfig({
    required this.micEnabled,
    required this.speakerEnabled,
    required this.mode,
    this.micDeviceId,
    this.speakerDeviceId,
    required this.modelPath,
    required this.vadEnabled,
    required this.sampleRate,
    required this.chunkDurationSecs,
  });

  static Future<SessionConfig> forMode({
    required SessionMode mode,
    required String modelPath,
  }) => RustLib.instance.api.crateAudioSessionConfigForMode(
    mode: mode,
    modelPath: modelPath,
  );

  @override
  int get hashCode =>
      micEnabled.hashCode ^
      speakerEnabled.hashCode ^
      mode.hashCode ^
      micDeviceId.hashCode ^
      speakerDeviceId.hashCode ^
      modelPath.hashCode ^
      vadEnabled.hashCode ^
      sampleRate.hashCode ^
      chunkDurationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionConfig &&
          runtimeType == other.runtimeType &&
          micEnabled == other.micEnabled &&
          speakerEnabled == other.speakerEnabled &&
          mode == other.mode &&
          micDeviceId == other.micDeviceId &&
          speakerDeviceId == other.speakerDeviceId &&
          modelPath == other.modelPath &&
          vadEnabled == other.vadEnabled &&
          sampleRate == other.sampleRate &&
          chunkDurationSecs == other.chunkDurationSecs;
}

enum SessionMode {
  webinar,
  online,
  offline;

  Future<(bool, bool)> defaultToggles() =>
      RustLib.instance.api.crateAudioSessionModeDefaultToggles(that: this);

  Future<bool> echoDedupeEnabled() =>
      RustLib.instance.api.crateAudioSessionModeEchoDedupeEnabled(that: this);
}
