// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`

@freezed
sealed class TrascribeError with _$TrascribeError implements FrbException {
  const TrascribeError._();

  const factory TrascribeError.audioDevice(String field0) =
      TrascribeError_AudioDevice;
  const factory TrascribeError.audioDecode(String field0) =
      TrascribeError_AudioDecode;
  const factory TrascribeError.model(String field0) = TrascribeError_Model;
  const factory TrascribeError.transcription(String field0) =
      TrascribeError_Transcription;
  const factory TrascribeError.export_(String field0) = TrascribeError_Export;

  /// String, not `std::io::Error` — the latter has no FRB `SseEncode`
  /// impl, which broke bridge codegen. Construct via
  /// `TrascribeError::from(io_err)` or `.map_err(TrascribeError::from)`.
  const factory TrascribeError.io(String field0) = TrascribeError_Io;
  const factory TrascribeError.invalidInput(String field0) =
      TrascribeError_InvalidInput;
  const factory TrascribeError.sessionNotFound(String field0) =
      TrascribeError_SessionNotFound;
}
