// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'audio.dart';
import 'audio/capture.dart';
import 'audio/device.dart';
import 'audio/loopback.dart';
import 'audio/loopback/macos.dart';
import 'dart:async';
import 'dart:convert';
import 'decode.dart';
import 'error.dart';
import 'export.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'session.dart';
import 'settings.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_JoinHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SenderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SenderVecF32Ptr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32;

  @protected
  JoinHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    dynamic raw,
  );

  @protected
  Sender
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    dynamic raw,
  );

  @protected
  SenderVecF32
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    dynamic raw,
  );

  @protected
  JoinHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    dynamic raw,
  );

  @protected
  Sender
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    dynamic raw,
  );

  @protected
  SenderVecF32
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  AudioBuffer dco_decode_audio_buffer(dynamic raw);

  @protected
  AudioCapture dco_decode_audio_capture(dynamic raw);

  @protected
  AudioDeviceInfo dco_decode_audio_device_info(dynamic raw);

  @protected
  AutoSplitReason dco_decode_auto_split_reason(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  JoinHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    dynamic raw,
  );

  @protected
  Sender
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    dynamic raw,
  );

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  AutoSplitReason dco_decode_box_autoadd_auto_split_reason(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  Segment dco_decode_box_autoadd_segment(dynamic raw);

  @protected
  SessionConfig dco_decode_box_autoadd_session_config(dynamic raw);

  @protected
  SessionRecoverySnapshot dco_decode_box_autoadd_session_recovery_snapshot(
    dynamic raw,
  );

  @protected
  ExportFormat dco_decode_export_format(dynamic raw);

  @protected
  ExportedFile dco_decode_exported_file(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<AudioDeviceInfo> dco_decode_list_audio_device_info(dynamic raw);

  @protected
  List<ExportFormat> dco_decode_list_export_format(dynamic raw);

  @protected
  List<ExportedFile> dco_decode_list_exported_file(dynamic raw);

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Segment> dco_decode_list_segment(dynamic raw);

  @protected
  List<SessionEvent> dco_decode_list_session_event(dynamic raw);

  @protected
  List<SessionRecoverySnapshot> dco_decode_list_session_recovery_snapshot(
    dynamic raw,
  );

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  JoinHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    dynamic raw,
  );

  @protected
  Sender?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    dynamic raw,
  );

  @protected
  AutoSplitReason? dco_decode_opt_box_autoadd_auto_split_reason(dynamic raw);

  @protected
  (BigInt, BigInt)? dco_decode_opt_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  (bool, bool) dco_decode_record_bool_bool(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw);

  @protected
  Segment dco_decode_segment(dynamic raw);

  @protected
  SessionConfig dco_decode_session_config(dynamic raw);

  @protected
  SessionEvent dco_decode_session_event(dynamic raw);

  @protected
  SessionMode dco_decode_session_mode(dynamic raw);

  @protected
  SessionRecoverySnapshot dco_decode_session_recovery_snapshot(dynamic raw);

  @protected
  SessionStatus dco_decode_session_status(dynamic raw);

  @protected
  Theme dco_decode_theme(dynamic raw);

  @protected
  TrascribeError dco_decode_trascribe_error(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  JoinHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    SseDeserializer deserializer,
  );

  @protected
  Sender
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    SseDeserializer deserializer,
  );

  @protected
  SenderVecF32
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    SseDeserializer deserializer,
  );

  @protected
  JoinHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    SseDeserializer deserializer,
  );

  @protected
  Sender
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    SseDeserializer deserializer,
  );

  @protected
  SenderVecF32
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  AudioBuffer sse_decode_audio_buffer(SseDeserializer deserializer);

  @protected
  AudioCapture sse_decode_audio_capture(SseDeserializer deserializer);

  @protected
  AudioDeviceInfo sse_decode_audio_device_info(SseDeserializer deserializer);

  @protected
  AutoSplitReason sse_decode_auto_split_reason(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  JoinHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    SseDeserializer deserializer,
  );

  @protected
  Sender
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    SseDeserializer deserializer,
  );

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  AutoSplitReason sse_decode_box_autoadd_auto_split_reason(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  Segment sse_decode_box_autoadd_segment(SseDeserializer deserializer);

  @protected
  SessionConfig sse_decode_box_autoadd_session_config(
    SseDeserializer deserializer,
  );

  @protected
  SessionRecoverySnapshot sse_decode_box_autoadd_session_recovery_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  ExportFormat sse_decode_export_format(SseDeserializer deserializer);

  @protected
  ExportedFile sse_decode_exported_file(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<AudioDeviceInfo> sse_decode_list_audio_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ExportFormat> sse_decode_list_export_format(
    SseDeserializer deserializer,
  );

  @protected
  List<ExportedFile> sse_decode_list_exported_file(
    SseDeserializer deserializer,
  );

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Segment> sse_decode_list_segment(SseDeserializer deserializer);

  @protected
  List<SessionEvent> sse_decode_list_session_event(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionRecoverySnapshot> sse_decode_list_session_recovery_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  JoinHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    SseDeserializer deserializer,
  );

  @protected
  Sender?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    SseDeserializer deserializer,
  );

  @protected
  AutoSplitReason? sse_decode_opt_box_autoadd_auto_split_reason(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt)? sse_decode_opt_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (bool, bool) sse_decode_record_bool_bool(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

  @protected
  Segment sse_decode_segment(SseDeserializer deserializer);

  @protected
  SessionConfig sse_decode_session_config(SseDeserializer deserializer);

  @protected
  SessionEvent sse_decode_session_event(SseDeserializer deserializer);

  @protected
  SessionMode sse_decode_session_mode(SseDeserializer deserializer);

  @protected
  SessionRecoverySnapshot sse_decode_session_recovery_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer);

  @protected
  Theme sse_decode_theme(SseDeserializer deserializer);

  @protected
  TrascribeError sse_decode_trascribe_error(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    JoinHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    Sender self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    SenderVecF32 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    JoinHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    Sender self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    SenderVecF32 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_audio_buffer(AudioBuffer self, SseSerializer serializer);

  @protected
  void sse_encode_audio_capture(AudioCapture self, SseSerializer serializer);

  @protected
  void sse_encode_audio_device_info(
    AudioDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auto_split_reason(
    AutoSplitReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    JoinHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    Sender self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_auto_split_reason(
    AutoSplitReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_segment(Segment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_config(
    SessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_recovery_snapshot(
    SessionRecoverySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_format(ExportFormat self, SseSerializer serializer);

  @protected
  void sse_encode_exported_file(ExportedFile self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_device_info(
    List<AudioDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_export_format(
    List<ExportFormat> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_exported_file(
    List<ExportedFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_segment(List<Segment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_session_event(
    List<SessionEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_recovery_snapshot(
    List<SessionRecoverySnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    JoinHandle? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    Sender? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_auto_split_reason(
    AutoSplitReason? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_bool_bool((bool, bool) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_segment(Segment self, SseSerializer serializer);

  @protected
  void sse_encode_session_config(SessionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_session_event(SessionEvent self, SseSerializer serializer);

  @protected
  void sse_encode_session_mode(SessionMode self, SseSerializer serializer);

  @protected
  void sse_encode_session_recovery_snapshot(
    SessionRecoverySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_theme(Theme self, SseSerializer serializer);

  @protected
  void sse_encode_trascribe_error(
    TrascribeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSender(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderVecf32(
    int ptr,
  );
}
