// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'export.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session.freezed.dart';

@freezed
sealed class SessionEvent with _$SessionEvent {
  const SessionEvent._();

  const factory SessionEvent.transcript(Segment field0) =
      SessionEvent_Transcript;
  const factory SessionEvent.vu({
    required String source,
    required double level,
  }) = SessionEvent_Vu;
}

class SessionRecoverySnapshot {
  final String sessionId;
  final SessionConfig config;
  final BigInt startedAtUnixMs;
  final BigInt lastSplitAtUnixMs;
  final int segmentsCount;

  const SessionRecoverySnapshot({
    required this.sessionId,
    required this.config,
    required this.startedAtUnixMs,
    required this.lastSplitAtUnixMs,
    required this.segmentsCount,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      config.hashCode ^
      startedAtUnixMs.hashCode ^
      lastSplitAtUnixMs.hashCode ^
      segmentsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionRecoverySnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          config == other.config &&
          startedAtUnixMs == other.startedAtUnixMs &&
          lastSplitAtUnixMs == other.lastSplitAtUnixMs &&
          segmentsCount == other.segmentsCount;
}

class SessionStatus {
  final String sessionId;
  final double elapsedSeconds;
  final bool micEnabled;
  final bool speakerEnabled;
  final int segmentsCount;
  final bool modelLoaded;

  const SessionStatus({
    required this.sessionId,
    required this.elapsedSeconds,
    required this.micEnabled,
    required this.speakerEnabled,
    required this.segmentsCount,
    required this.modelLoaded,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      elapsedSeconds.hashCode ^
      micEnabled.hashCode ^
      speakerEnabled.hashCode ^
      segmentsCount.hashCode ^
      modelLoaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionStatus &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          elapsedSeconds == other.elapsedSeconds &&
          micEnabled == other.micEnabled &&
          speakerEnabled == other.speakerEnabled &&
          segmentsCount == other.segmentsCount &&
          modelLoaded == other.modelLoaded;
}
