// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppConfig {
  final String? recordingsDir;
  final String? onStop;
  final bool? transcriptionEnabled;
  final bool? doctorCheckOnStart;

  const AppConfig({
    this.recordingsDir,
    this.onStop,
    this.transcriptionEnabled,
    this.doctorCheckOnStart,
  });

  @override
  int get hashCode =>
      recordingsDir.hashCode ^
      onStop.hashCode ^
      transcriptionEnabled.hashCode ^
      doctorCheckOnStart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          recordingsDir == other.recordingsDir &&
          onStop == other.onStop &&
          transcriptionEnabled == other.transcriptionEnabled &&
          doctorCheckOnStart == other.doctorCheckOnStart;
}

class AppSettings {
  final Theme theme;
  final String defaultModel;
  final SessionMode defaultMode;
  final String libraryPath;
  final bool alwaysOnTop;
  final int autoSaveIntervalSecs;
  final bool vadEnabled;
  final bool echoDedupeEnabled;
  final String? language;

  const AppSettings({
    required this.theme,
    required this.defaultModel,
    required this.defaultMode,
    required this.libraryPath,
    required this.alwaysOnTop,
    required this.autoSaveIntervalSecs,
    required this.vadEnabled,
    required this.echoDedupeEnabled,
    this.language,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      defaultModel.hashCode ^
      defaultMode.hashCode ^
      libraryPath.hashCode ^
      alwaysOnTop.hashCode ^
      autoSaveIntervalSecs.hashCode ^
      vadEnabled.hashCode ^
      echoDedupeEnabled.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          defaultModel == other.defaultModel &&
          defaultMode == other.defaultMode &&
          libraryPath == other.libraryPath &&
          alwaysOnTop == other.alwaysOnTop &&
          autoSaveIntervalSecs == other.autoSaveIntervalSecs &&
          vadEnabled == other.vadEnabled &&
          echoDedupeEnabled == other.echoDedupeEnabled &&
          language == other.language;
}

enum Theme { light, dark }
