// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../error.dart';
import '../../frb_generated.dart';
import '../../lib.dart';
import '../capture.dart';
import '../loopback.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<AudioCapture> captureLoopback({
  String? deviceHint,
  required SenderVecF32 samplesTx,
}) => RustLib.instance.api.crateAudioLoopbackMacosCaptureLoopback(
  deviceHint: deviceHint,
  samplesTx: samplesTx,
);
