// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import '../lib.dart';
import 'capture.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<AudioCapture> startLoopback({
  String? deviceHint,
  required SenderVecF32 samplesTx,
}) => RustLib.instance.api.crateAudioLoopbackStartLoopback(
  deviceHint: deviceHint,
  samplesTx: samplesTx,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sender < Vec < f32 > >>>
abstract class SenderVecF32 implements RustOpaqueInterface {}
